= Adding Layered Packages 

Add a layered package with the `rpm-ostree install` command:

----
$ rpm-ostree install --help
Usage:
  rpm-ostree install [OPTION…] PACKAGE [PACKAGE...]

Overlay additional packages

Help Options:
  -h, --help              Show help options

Application Options:
  --uninstall=PKG         Remove overlayed additional package
  -C, --cache-only        Do not download latest ostree and RPM data
  --download-only         Just download latest ostree and RPM data, don't deploy
  --os=OSNAME             Operate on provided OSNAME
  -r, --reboot            Initiate a reboot after operation is complete
  -n, --dry-run           Exit after printing the transaction
  --allow-inactive        Allow inactive package requests
  --idempotent            Do nothing if package already (un)installed
  --unchanged-exit-77     If no overlays were changed, exit 77
  --sysroot=SYSROOT       Use system root SYSROOT (default: /)
  --peer                  Force a peer-to-peer connection instead of using the system message bus
  --version               Print version information and exit
----

== Install multiple packages

This command accepts multiple package names. 
To create less images, consider grouping compatable packages into a single command.
This will create a single new layered image.

----
$ sudo rpm-ostree install tree asciiquarium
----

Alternately, consider xref:container-support.adoc[using containers] for your applications.
A container workflow can be managed separately from the OS update cycle.

== Be sure to Reboot

At this point a new layer is available but not yet active. 
For example, the tree command installed above is not yet found.

----
$ tree 
bash: tree: command not found
----

Display the current status of the images:

----
$ rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
  ostree://fedora-iot:fedora/stable/x86_64/iot
                   Version: 29.20190211.0 (2019-02-11T13:18:27Z)
                BaseCommit: 5eb0553c02a8035a02f030c7fb8d5c6727d1ecb2700dade4b767363acfcab8e4
              GPGSignature: Valid signature by C2A3FA9DC67F68B98BB543F47BB90722DBBDCF7C
           LayeredPackages: asciiquarium tree   <1>

● ostree://fedora-iot:fedora/stable/x86_64/iot  <2>
                   Version: 29.20190211.0 (2019-02-11T13:18:27Z)
                    Commit: 5eb0553c02a8035a02f030c7fb8d5c6727d1ecb2700dade4b767363acfcab8e4
              GPGSignature: Valid signature by C2A3FA9DC67F68B98BB543F47BB90722DBBDCF7C

  ostree://fedora-iot:fedora/stable/x86_64/iot  <3>
                   Version: 29.20190207.0 (2019-02-07T17:55:35Z)
                    Commit: 26a3bb07a98402bbc3f39f7c1d07ec9ad05158e084141fdfba0b8c18e3cf0b5e
              GPGSignature: Valid signature by C2A3FA9DC67F68B98BB543F47BB90722DBBDCF7C
----

<1> The new image indicates layered packages.
<2> The second image listed is the active image as indicated by the ●.
<3> Any older images will be removed when the system is rebooted.


Due to the atomic nature of the OS, you will have to reboot into the new image to have the layered image take effect:

----
$ systemctl reboot
----

Display the status of the images:

----
$ rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora-iot:fedora/stable/x86_64/iot
                   Version: 29.20190211.0 (2019-02-11T13:18:27Z)
                BaseCommit: 5eb0553c02a8035a02f030c7fb8d5c6727d1ecb2700dade4b767363acfcab8e4
              GPGSignature: Valid signature by C2A3FA9DC67F68B98BB543F47BB90722DBBDCF7C
           LayeredPackages: asciiquarium tree

  ostree://fedora-iot:fedora/stable/x86_64/iot
                   Version: 29.20190211.0 (2019-02-11T13:18:27Z)
                    Commit: 5eb0553c02a8035a02f030c7fb8d5c6727d1ecb2700dade4b767363acfcab8e4
              GPGSignature: Valid signature by C2A3FA9DC67F68B98BB543F47BB90722DBBDCF7C
----

After the reboot, the tree command will be available:

----
$ tree /boot
/boot
├── grub2 [error opening dir]
├── loader -> loader.0
├── loader.0
│   ├── entries
│   │   ├── ostree-1-fedora-iot.conf
│   │   └── ostree-2-fedora-iot.conf
│   └── grub.cfg
├── lost+found [error opening dir]
└── ostree
    └── fedora-iot-91791ece38e982e98b40305668d499f6ccfca08696fd769e43349316293f3e4f
        ├── initramfs-4.20.7-200.fc29.x86_64.img
        └── vmlinuz-4.20.7-200.fc29.x86_64

7 directories, 5 files
----

