= Applying updates

NOTE: The latest image builds for x86_64 and aarch64 are available at https://download.fedoraproject.org/pub/alt/iot/[here]. 

Display the status of the currently running deployment:

----
$ rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora-iot:fedora/stable/x86_64/iot
                   Version: 29.20190207.0 (2019-02-07T17:55:35Z)
                    Commit: 26a3bb07a98402bbc3f39f7c1d07ec9ad05158e084141fdfba0b8c18e3cf0b5e
              GPGSignature: Valid signature by C2A3FA9DC67F68B98BB543F47BB90722DBBDCF7C
----

Check for available updates:

----
$ sudo rpm-ostree upgrade --check
AvailableUpdate:
        Version: 29.20190211.0 (2019-02-11T13:18:27Z)
         Commit: 5eb0553c02a8035a02f030c7fb8d5c6727d1ecb2700dade4b767363acfcab8e4
   GPGSignature: Valid signature by C2A3FA9DC67F68B98BB543F47BB90722DBBDCF7C
  SecAdvisories: 1 moderate
           Diff: 25 upgraded
----

Apply the available updates:

----
$ sudo rpm-ostree upgrade
----

Due to the atomic nature of the OS, you will have to reboot into the new image to have the updates take effect:

----
$ systemctl reboot
----

The `rpm-ostree` utility keeps two deployments available. 
Both have an entry in the bootloader menu and the new updated entry with be the default. 
If necessary, you can choose the other entry to boot into the previous deployment.

TIP: The timeout for GRUB2 to display the menu is very short at only one second. Pressing the space bar or an arrow key when the menu appears will interrupt the timeout and allow you to choose another entry. The ENTER key will boot the selected image. 

NOTE: More information on managing upgrades and rollbacks can be found in the xref:user-guide.adoc[User Guide]. 
