= Getting Started


Welcome to the getting started guide for Fedora IoT.
Both this guide and Fedora IoT images are in the very early stages, so please report any issues to https://lists.fedoraproject.org/admin/lists/iot.lists.fedoraproject.org/[the mailing list].

image::iot-fedora.svg[SoC board]

== Supported Platforms

For the moment, Fedora IoT supports the x86_64 and aarch64 architectures.
The components to support ARMv7 are being worked upon and will be added shortly.

Refer to the list of currently tested xref:reference-platforms.adoc[Reference Platforms]. The list of supported reference platforms will expand over time.
Other x86_64 or aarch64 platforms should work just fine but haven't been widely tested in the IoT context so your milage may vary.

If you're a hardware vendor and would like to have a device become a reference platform by actively participating and testing Fedora IoT,
please reach out to https://fedoraproject.org/wiki/User:Pbrobinson[Peter Robinson], the Fedora IoT Lead.

== Required Resources
The current images are 4GB in size and tested with 1GB of RAM.
The Fedora IoT base image should be able to run with less resources, but of course this will limit the amount of container applications that can be run on top of the base OS.

== Download Image

Fedora IoT images for download are available at the Fedora IoT https://iot.fedoraproject.org[landing page].

== Setup VM or Physical Device

- Follow these steps to xref:virtual-machine-setup.adoc[setup virtual machine]

- Follow these steps to xref:physical-device-setup.adoc[setup physical device]


Follow the setup instructions from xref:ignition.adoc[ignition]
