= Reference Platforms

Fedora IoT supports the aarch64 (arm64), ARMv7 (arm32) and x86_64 architectures.

These reference platforms have been tested and are known to work with Fedora IoT, however their inclusion on this list does not necessarily constitute a release-blocking issue should a bug that is specific to the hardware below be found.

The currently tested reference devices are as follows:

== aarch64 architecture

[frame="none",grid="none"]
|=======================
| KVM based VM (TianoCore UEFI) | SystemReady-SR Server Ready (SBSA/SBBR) | SystemReady-ES Embedded System Ready
| NVidia Jetson Xaver AGX | NVidia Jetson Xaver NX | NVidia Jetson nano 
| Raspberry Pi 4 (4B/CM4) | Raspberry Po 3 (3B/3B+)| 96boards Rock960 Consumer Edition
| Solid Run HummingBoard-M (i.MX8 based)| Pine64 Rockpro64 and Rock64 | Pine64 A64-LTS
|=======================

== ARMv7 architecture
* KVM ARMv7 virtual machine booting using TianoCore UEFI firmware
* Raspberry Pi 2 Model B, 3 Model B and 3 Model B+

== x86_64 architecture
* KVM x86_64 virtual machine booting using TianoCore UEFI firmware
* Compulabs Fitlet2
* Up Squared
* Generic Intel x86-64 products with UEFI

Other devices should work, but aren't being actively tested in the context of IoT.
The list of supported reference devices will expand with time.

== Required resources

The images being created are currently 4GB in size.
The current memory used for testing is 1GB of RAM.
The Fedora IoT base image should run with less,
but of course this limits the amount of container applications that can be run on top of the base OS.
