= Reference Platforms

For the moment Fedora supports the x86_64 and aarch64 architectures.
The components to support ARMv7 are being worked upon and will be added shortly.

These reference platforms have been tested and are known to work with Fedora IoT, however their inclusion on this list does not necessarily constitute a release-blocking issue should a bug that is specific to the hardware below be found.

The currently tested reference devices are as follows:

* x86_64, aarch64 and ARMv7 virtual machines
* Raspberry Pi 3 Model B and Raspberry Pi 3 Model B+
* 96boards Rock960 Consumer Edition
* Pine64 A64-LTS
* Pine64 Rockpro64 and Rock64
* Up Squared

Other devices should work, but aren't being actively tested in the context of IoT.
The list of supported reference devices will expand with time.

== Required resources

The images being created are currently 4GB in size.
The current memory used for testing is 1GB of RAM.
The Fedora IoT base image should run with less,
but of course this limits the amount of container applications that can be run on top of the base OS.
