= Reference Platforms

Fedora IoT supports the aarch64 (arm64), ARMv7 (arm32) and x86_64 architectures.

We only actively support UEFI plaforms so if your device doesn't boot with UEFI it probably won't work.

These reference platforms have been tested and are known to work with Fedora IoT, however their inclusion on this list does not necessarily constitute a release-blocking issue should a bug that is specific to the hardware below be found.

The currently tested reference devices are as follows:

== aarch64 (arm64) architecture

[cols="3*a",frame="none",grid="none",align="center"]
|===
| SystemReady-SR Server Ready (SBSA/SBBR)
| SystemReady-ES Embedded System Ready
| SystemReady-IR IoT Ready

| KVM based VM (TianoCore UEFI)
| NVidia Jetson Xaver AGX
| NVidia Jetson Xaver NX

| Raspberry Pi 4 (4B/CM4)
| Raspberry Pi 3 (3B/3B+/3CM)
| 96boards Rock960 Consumer Edition

| Solid Run HummingBoard-M (i.MX8 based)
| Pine64 Rockpro64 and Rock64
| Pine64 A64-LTS and SoPine
|===

== ARMv7 (arm32) architecture

[cols="3*a",frame="none",grid="none",align="center"]
|===
| KVM based VM (TianoCore UEFI)
| SystemReady-IR IoT Ready
| Raspberry Pi 3 (3B/3B+/3CM)

| Raspberry Pi 2B
|
|
|===

== x86_64 architecture

[cols="3*a",frame="none",grid="none",align="center"]
|===
| KVM based VM (TianoCore UEFI)
| Compulabs Fitlet2
| Up Squared

| Generic Intel x86-64 products with UEFI
|
|
|===

Other devices should work, but aren't being actively tested in the context of IoT.
The list of supported reference devices will expand with time.

== Required resources

The images being created are currently 4GB in size.
The current memory used for testing is 1GB of RAM.
The Fedora IoT base image should run with less,
but of course this limits the amount of container applications that can be run on top of the base OS.
