= Fedora IoT Working Group
:url-irc: https://web.libera.chat/?channel=#fedora-iot
:url-matrix: https://matrix.to/#/#iot:fedoraproject.org

The Fedora IoT Working Group develops and maintains the xref:iot::index.adoc[Fedora IoT Edition].
If you'd like to join us, introduce yourself and pitch in!

== Communications

We primarily communicate by the https://lists.fedoraproject.org/admin/lists/iot.lists.fedoraproject.org/[Fedora IoT mailing list] and the {url-irc}[#fedora-iot IRC channel on Libera.Chat] (bridged to {url-matrix}[#iot on chat.fedoraproject.org]).
Check the https://calendar.fedoraproject.org/IoT/[IoT calendar] for meeting times and locations.

== Contributing to Fedora IoT

There's a number of components that make up Fedora IoT.
The upstream source components for general projects like the Zezere and Greenboot reside on the https://github.com/fedora-iot/[Fedora IoT GitHub page].

For the source for Fedora specific things like compose configs and docs we have the https://pagure.io/group/fedora-iot[Fedora IoT] Pagure organisation which contains the various git repositories for building Fedora IoT.
This includes the https://pagure.io/fedora-iot/issues[core issue tracker].
