= Fedora IoT Working Group
:url-irc: https://web.libera.chat/?channel=#fedora-iot
:url-matrix: https://matrix.to/#/#iot:fedoraproject.org

The Fedora IoT Working Group develops and maintains the xref:iot::index.adoc[Fedora IoT Edition].
If you'd like to join us, introduce yourself and pitch in!

== Communications

We primarily communicate by the https://lists.fedoraproject.org/admin/lists/iot.lists.fedoraproject.org/[Fedora IoT mailing list] and the {url-irc}[#fedora-iot IRC channel on Libera.Chat] (bridged to {url-matrix}[#iot on chat.fedoraproject.org]).
Check the https://calendar.fedoraproject.org/IoT/[IoT calendar] for meeting times and locations.

== Contributing to Fedora IoT

There's a number of components that make up Fedora IoT.
The upstream source components for general projects like the Zezere and Greenboot reside on the https://github.com/fedora-iot/[Fedora IoT GitHub page].

For the source for Fedora specific things like compose configs, we have the https://pagure.io/group/fedora-iot[Fedora IoT] Pagure organisation which contains the various git repositories for building Fedora IoT.

Docs and upstream component sources are on https://github.com/fedora-iot[GitHub].

Bugs are tracked in Red Hat Bugzilla using the https://bugzilla.redhat.com/show_bug.cgi?id=IoT[IoT tracker bug] for bugs reported against other components and the https://bugzilla.redhat.com/buglist.cgi?component=IoT&product=Fedora[IoT compoenent] for IoT-specific issues.
