include::_attributes.adoc[]

= Quick firmware update with the Coreos Installer

== Overview 
The Coreos Installer tool, run from the simplified provisioner ISO file, allows technicians to update the firmware on a controller device for immediate use.

It does this by bypassing the usual user setup process and jumping to a direct install of a preconfigured OS "snapshot".

To initiate this process for physical hardware, first either save the ISO file to a flash drive and then insert it into the controller or edge device you'd like to update, Alternatively for virtual machine server setups, simply run an install command from the Linux command prompt.

== Installing with a USB flash drive

1. Copy the ISO file to a USB flash drive with no less than 8 GB of storage capacity.
2. Connect the USB flash drive to the port of the controller you wish to update the firmware on.


== Installing on virtual machines for server

1. Use the `virt-install`
command to boot from the Simplified Provisioner ISO.
+
[subs="attributes"]
....
# virt-install --connect qemu:///system \
               --name "{VMName}" \
               --os-variant "{OSVariant}" \
               --boot uefi,loader.secure=false \
               --vcpus {VMCPUs} --memory {VMMemory} \
               --network network=default,model=virtio \
               --disk pool=default,size=30 \
               --cdrom {FedoraSimplifiedProvisionerISO}
....
 
== Boot the Simplified Provisioner from UEFI HTTP Boot

1. Copy the contents of the Simplified Provisioner ISO to a directory
+
[subs="attributes"]
....
mount {FedoraSimplifiedProvisionerISO} /mnt
cp -r /mnt Fedora-{FedoraVersion}-IoT-Simplified-Provisioner
cd Fedora-{FedoraVersion}-IoT-Simplified-Provisioner
....
* Modify the `grub.cfg` file in `EFI/BOOT` directory and replace all the
instances of `linux` and `initrd` with `linuxefi` and `initrdefi` respectively.
+
[subs="attributes"]
....
sed -i -e 's|linux /|linuxefi /|' \
       -e 's|initrd /|initrdefi /|' \
       EFI/BOOT/grub.cfg
....
* Use an HTTP Server to serve the contents over the network, e.g.:
+
[subs="attributes"]
....
python3 -m http.server {UEFIHTTPBootServerPort}
firewall-cmd --add-port={UEFIHTTPBootServerPort}/tcp
....

* The correct URL to perform UEFI HTTPBoot depends on the ISO architecture (`x86_64` or `aarch64`)
** For `x86_64` hardware the corresponding HTTP URL of
`EFI/BOOT/BOOTX86.EFI` file will be used to boot (e.g. `http://{UEFIHTTPBootServerIP}:{UEFIHTTPBootServerPort}/EFI/BOOT/BOOTX86.EFI`)
** For `aarch64` hardware the corresponding HTTP URL of
`EFI/BOOT/BOOTAA64.EFI` file will be used to boot (e.g. `http://{UEFIHTTPBootServerIP}:{UEFIHTTPBootServerPort}/EFI/BOOT/BOOTAA64.EFI`)

=== Booting Physical Servers

* If using a physical server please check the manual or Management UI interface
to see if the system supports UEFI HTTPBoot and follow the steps in the manual
to boot it manually or in an automated way from the boot URL (see above)

=== Booting Virtual Machines

* Use the `virt-install` command (or any other tool that supports booting UEFI VMs) to boot a VM. E.g.:
+
[subs="attributes"]
....
virt-install --connect qemu:///system \
             --name "{VMName}" \
             --os-variant "{OSVariant}" \
             --boot uefi,loader.secure=false \
             --vcpus {VMCPUs} --memory {VMMemory}  \
             --network network=default,model=virtio \
             --disk pool=default,size=30 \
             --import
....

* Press *"[Esc]"* key repeately to enter the UEFI management interface
* Select *"Device Manager"* and press *"[Enter]"*
* Select *"Network Device List"* and press *"[Enter]"*
* Select the MAC address corresponding to the interface you wan to use to perform UEFI HTTPBoot and press *"[Enter]"*
* Select *"HTTP Boot Configuration"* and press *"[Enter]"*
* Select *"Boot URI"* and press *"[Enter]"*
* Enter the HTTPBoot URL (see above) (e.g.: *http://{UEFIHTTPBootServerIP}:{UEFIHTTPBootServerPort}/EFI/BOOT/BOOTX86.EFI*) and press *"[Enter]"*
* Press *"[F10]"* key to save the changes and then press *"[Y]"* to confirm the action
* Press *"[Esc]"* four times until you return to the main screen
* Select *"Boot Manager"*
* Select *"UEFI HTTP"* and press *"[Enter]"*
* The VM should perform the UEFI HTTPBoot.

It's also possible to perform the same steps in an automated way by modifying the UEFI vars after creating the virtual
machine. For that we will need to install the `qemu-img` and `python3-virt-firmware` packages:
[subs="attributes"]
....
dnf install -y python3-virt-firmware qemu-img
....

* Create an unitialized and stopped virtual machine (make sure it supports UEFI), e.g.:
+
[subs="attributes"]
....
virt-install --connect qemu:///system \
             --name "{VMName}" \
             --os-variant "{OSVariant}" \
             --boot uefi,loader.secure=false \
             --vcpus {VMCPUs} --memory {VMMemory}  \
             --network network=default,model=virtio \
             --disk pool=default,size=30 \
             --import --noautoconsole --noreboot
....
* Connect the QCOW2 containing the VM's UEFI variables to an NBD disk so we can modify them inplace:
+
[subs="attributes"]
....
modprobe nbd
qemu-nbd --connect /dev/nbd0 /var/lib/libvirt/qemu/nvram/{VMName}_VARS.qcow2
....
* Use the `virt-fw-vars` tool to modify the UEFI variables and configure the VM to boot from the HTTP URL, e.g.:
+
[subs="attributes"]
....
virt-fw-vars --input /dev/nbd0 --set-boot-uri http://{UEFIHTTPBootServerIP}:{UEFIHTTPBootServerPort}/EFI/BOOT/BOOTX64.EFI
....
* Disconnect the NBD device:
+
[subs="attributes"]
....
qemu-nbd --disconnect /dev/nbd0
....
* Start the VM:
+
[subs="attributes"]
....
virsh --connect qemu:///system \
      start {VMName}
....
* The VM should perform an UEFI HTTPBoot from the configured URL

