= Contribute to Fedora IoT Edition
:url-irc: https://web.libera.chat/?channel=#fedora-iot
:url-matrix: https://matrix.to/#/#iot:fedoraproject.org

Fedora IoT is made up of many components, including a lot that are part of the main Fedora project, so there is a number of places where you may contribute.
This is by no means a canonical source for contribution, if you don't see an area where which seems to match please see the getting help section for general ways to engage with us to get answers to your questions.

If you're interested in joining the Fedora IoT Working Group, check out the xref:iot-wg::index.adoc[IoT WG docs].

== Reporting IoT bugs

If you are seeing issues with software that is included in the Fedora IoT Edition that is not necessarily specific to IoT the bug should be reported against the specific Fedora component.
There's details on how to do that in the https://docs.fedoraproject.org/en-US/quick-docs/bugzilla-file-a-bug/[how to file a bug] doc.

If you know which component the bug is in, file a bug in https://bugzilla.redhat.com[Red Hat Bugzilla] against the _Fedora_ product and the component in question.
Set the bug to block the https://bugzilla.redhat.com/show_bug.cgi?id=IoT[IoT Bugzilla tracker].

If you don't know which component to use or would to request a new package or feature be added to Fedora IoT,  you can file an issue in the https://github.com/fedora-iot/iot-distro/issues/new/choose[IoT Distro] Issue tracker in Github.

The provisioning portal is a project called Zezere.
You can report bugs and file feature requests on the https://github.com/fedora-iot/zezere[Zezere project page].

== Getting IoT help

We primarily communicate by the https://lists.fedoraproject.org/admin/lists/iot.lists.fedoraproject.org/[Fedora IoT mailing list] and the {url-irc}[#fedora-iot IRC channel on Libera.Chat] (bridged to {url-matrix}[#iot on chat.fedoraproject.org]).
