include::_attributes.adoc[]

= Setup a device by using FDO and the Simplified Installer
:toc:

== Prerequisites

* You have installed and configured the FDO services as described in:
** xref:fdo-installing-the-manufacturing-server-package.adoc[Installing and configuring the Manufacturing server]
** xref:fdo-installing-configuring-and-running-the-rendezvous-server.adoc[Installing and configuring the Rendezvous Server]
** xref:fdo-installing-configuring-and-running-the-owner-server.adoc[Installing and configuring the Owner's Onboarding Server]
* You have downloaded the link:http://iot.fedoraproject.org[Simplified Installer ISO image].
* If using libvirt make sure the FDO server ports are reachable from the VMs
+
[subs="attributes"]
....
# firewall-cmd --zone libvirt \
               --add-port={ManufacturingServerPort}/tcp \
               --add-port={OwnerOnboardingServerPort}/tcp \
               --add-port={RendezvousServerPort}/tcp \
               --permanent
# systemctl restart firewalld
....

== Boot the Simplified Installer

Boot the Simplified Installer from one of the sources below:

=== Boot from the Simplified Installer ISO

If you are using Virtual Machines, you can use the `virt-install`
command to boot from the Simplified installer ISO.
[subs="attributes"]
....
# virt-install --connect qemu:///system \
               --name "{VMName}" \
               --os-variant "{OSVariant}" \
               --boot uefi,loader.secure=false \
               --vcpus {VMCPUs} --memory {VMMemory} \
               --network network=default,model=virtio \
               --disk pool=default,size=30 \
               --cdrom {FedoraSimplifiedInstallerISO}
....

If you are using physical devices with a CD-ROM unit:

* Burn the downloaded Simplified Installer ISO to a CD-ROM
* Use the CD-ROM to boot the IoT device from it.

Continue by xref:fdo-device-setup.adoc#_edit_the_boot_parameters[editing the boot parameters]

=== Boot the Simplified Installer from an USB Flash Drive

* Copy the ISO image file to a USB flash drive (You will need a 8 GB USB flash drive at least)
* Connect the USB flash drive to the port of the computer you want to boot.
* Boot the ISO image from the USB flash drive.
* Continue by xref:fdo-device-setup.adoc#_edit_boot_parameters[editing the boot parameters]

=== Boot the Simplified Installer from UEFI HTTP Boot

* Copy the contents of the Simplified Installer ISO to a directory
+
[subs="attributes"]
....
mount {FedoraSimplifiedInstallerISO} /mnt
cp -r /mnt Fedora-{FedoraVersion}-IoT-Simplified-Installer
cd Fedora-{FedoraVersion}-IoT-Simplified-Installer
....
* Modify the `grub.cfg` file in `EFI/BOOT` directory and replace all the
instances of `linux` and `initrd` with `linuxefi` and `initrdefi` respectively
and add the FDO Manufacturing Server URL and the DIUN parameters to the `linuxefi`
entries.
+
[subs="attributes"]
....
sed -i -e 's|linux /|linuxefi /|' \
       -e 's|initrd /|initrdefi /|' \
       -e '/linuxefi/ s|$| fdo.manufacturing_server_url=http://{ManufacturingServerIP}:{ManufacturingServerPort}|' \
       -e '/linuxefi/ s|$| fdo.diun_pub_key_insecure=true|' \
       EFI/BOOT/grub.cfg
....
* Use an HTTP Server to serve the contents over the network, e.g.:
+
[subs="attributes"]
....
python3 -m http.server {UEFIHTTPBootServerPort}
firewall-cmd --add-port={UEFIHTTPBootServerPort}/tcp
....

* The correct URL to perform UEFI HTTPBoot depends on the ISO architecture (`x86_64` or `aarch64`)
** For `x86_64` hardware the corresponding HTTP URL of
`EFI/BOOT/BOOTX86.efi` file will be used to boot (e.g. `http://{UEFIHTTPBootServerIP}:{UEFIHTTPBootServerPort}/EFI/BOOT/BOOTX86.efi`)
** For `aarch64` hardware the corresponding HTTP URL of
`EFI/BOOT/BOOTAA64.efi` file will be used to boot (e.g. `http://{UEFIHTTPBootServerIP}:{UEFIHTTPBootServerPort}/EFI/BOOT/BOOTAA64.efi`)

==== Booting Physical Servers

* If using a physical server please check the manual or Management UI interface
to see if the system supports UEFI HTTPBoot and follow the steps in the manual
to boot it manually or in an automated way from the boot URL (see above)
* Once the physical server setup is correct it should perform an UEFI HTTPBoot
from the configured URL, perform the installation, the manufacturing processes
and shutdown.
* The next time the pyshical server is booted it will try to perform the FIDO
Device Onboarding process.
* Continue by xref:fdo-device-setup.adoc#_verify_the_onboarding[verifying the onboarding]

==== Booting Virtual Machines

* Use the `virt-install` command (or any other tool that supports booting UEFI VMs) to boot a VM. E.g.:
+
[subs="attributes"]
....
virt-install --connect qemu:///system \
             --name "{VMName}" \
             --os-variant "{OSVariant}" \
             --boot uefi,loader.secure=false \
             --vcpus {VMCPUs} --memory {VMMemory}  \
             --network network=default,model=virtio \
             --disk pool=default,size=30 \
             --import
....

* Press *"[Esc]"* key repeately to enter the UEFI management interface
* Select *"Device Manager"* and press *"[Enter]"*
* Select *"Network Device List"* and press *"[Enter]"*
* Select the MAC address corresponding to the interface you wan to use to perform UEFI HTTPBoot and press *"[Enter]"*
* Select *"HTTP Boot Configuration"* and press *"[Enter]"*
* Select *"Boot URI"* and press *"[Enter]"*
* Enter the HTTPBoot URL (see above) (e.g.: *http://{UEFIHTTPBootServerIP}:{UEFIHTTPBootServerPort}/EFI/BOOT/BOOTX86.efi*) and press *"[Enter]"*
* Press *"[F10]"* key to save the changes and then press *"[Y]"* to confirm the action
* Press *"[Esc]"* four times until you return to the main screen
* Select *"Boot Manager"*
* Select *"UEFI HTTP"* and press *"[Enter]"*
* The VM should perform an UEFI HTTPBoot, perform the installation, the manufacturing processes and shutdown.
* The next time the VM is booted it will try to perform the FIDO Device Onboarding process.
* Continue by xref:fdo-device-setup.adoc#_verify_the_onboarding[verifying the onboarding]

It's also possible to perform the same steps in an automated way by modifying the UEFI vars after creating the virtual
machine. For that we will need to install the `qemu-img` and `python3-virt-firmware` packages:
[subs="attributes"]
....
dnf install -y python3-virt-firmware qemu-img
....

* Create an unitialized and stopped virtual machine (make sure it supports UEFI), e.g.:
+
[subs="attributes"]
....
virt-install --connect qemu:///system \
             --name "{VMName}" \
             --os-variant "{OSVariant}" \
             --boot uefi,loader.secure=false \
             --vcpus {VMCPUs} --memory {VMMemory}  \
             --network network=default,model=virtio \
             --disk pool=default,size=30 \
             --import --noautoconsole --noreboot
....
* Connect the QCOW2 containing the VM's UEFI variables to an NBD disk so we can modify them inplace:
+
[subs="attributes"]
....
modprobe nbd
qemu-nbd --connect /dev/nbd0 /var/lib/libvirt/qemu/nvram/{VMName}_VARS.qcow2
....
* Use the `virt-fw-vars` tool to modify the UEFI variables and configure the VM to boot from the HTTP URL, e.g.:
+
[subs="attributes"]
....
virt-fw-vars --input /dev/nbd0 --set-boot-uri http://{UEFIHTTPBootServerIP}:{UEFIHTTPBootServerPort}/EFI/BOOT/BOOTX64.EFI
....
* Disconnect the NBD device:
+
[subs="attributes"]
....
qemu-nbd --disconnect /dev/nbd0
....
* Start the VM:
+
[subs="attributes"]
....
virsh --connect qemu:///system \
      start {VMName}
....
* The VM should perform an UEFI HTTPBoot, perform the installation, the manufacturing processes and shutdown.
* The next time the VM is booted it will try to perform the FIDO Device Onboarding process.
* Continue by xref:fdo-device-setup.adoc#_verify_the_onboarding[verifying the onboarding]


== Edit the boot parameters

Once device has been booted from the Simplified Installer the boot menu shows
following options:
[subs="attributes"]
....
Install Fedora {FedoraVersion}
Test this media & install Fedora {FedoraVersion}
Troubleshooting -->
....

* Select *"Install Fedora {FedoraVersion}"* and press the *"[e]"* key to edit the menu entry.
* Make sure the installation device variable (`coreos.inst.install_dev`) is correct and
append the manufacturing parameters
(`fdo.manufacturing_server_url=http://{ManufacturingServerIP}:{ManufacturingServerPort} fdo.diun_pub_key_insecure=true`)
to the `linux` line if not present:
+
[subs="attributes"]
....
### BEGIN /etc/grub.d/10_linux ###
menuentry 'Install Fedora {FedoraVersion}' --class fedora --class gnu-linux --class gnu --class os {
	linux  images/pxeboot/vmlinuz rd.neednet=1 coreos.inst.crypt_root=1 coreos.inst.isoroot=Fedora-{FedoraVersion}-IoT-x86_64 coreos.inst.install_dev=/dev/vda coreos.inst.image_file=/run/media/iso/image.raw.xz coreos.inst.insecure quiet fdo.manufacturing_server_url=http://{ManufacturingServerIP}:{ManufacturingServerPort} fdo.diun_pub_key_insecure=true
	initrd images/pxeboot/initrd.img
}
....
* Boot the menu entry by pressing *"[Ctrl-x]"*
* Once the IoT device has been installed and performed the manufacturing process it will reboot and perform the FDO Onboarding in the next boot.

== Verifying the Onboarding

If the onboarding finished successfully you sould be able to login with the initial user configured in the Service Info API server.

When using libvirt in the same host where the FDO services are running you can use the following command to connect to the VM:
[subs="attributes"]
....
#! /bin/bash

export LIBVIRT_DEFAULT_URI=qemu:///system
export LIBVIRT_DOMAIN_NAME={VMName}
export LIBVIRT_NETWORK=default

MAC=$(virsh domiflist "$\{LIBVIRT_DOMAIN_NAME\}" | grep "$\{LIBVIRT_NETWORK\}" | awk '{print $5}')
IP=$(virsh net-dhcp-leases "$\{LIBVIRT_NETWORK\}"| grep "$\{MAC\}" | awk '{print $5}'| cut -f1 -d/)
ssh admin@$\{IP\}
....

