= Getting Started


Welcome to the getting started guide for Fedora IoT.
Both this guide and Fedora IoT images are in the very early stages, so please report any issues to https://lists.fedoraproject.org/admin/lists/iot.lists.fedoraproject.org/[the mailing list].

image::iot-fedora.svg[SoC board]

== Supported Platforms

Fedora IoT supports the x86_64 and aarch64 architectures.

Refer to the list of currently tested xref:reference-platforms.adoc[Reference Platforms]. The list of supported reference platforms will expand over time.
Other x86_64 or aarch64 platforms should work just fine but haven't been widely tested in the IoT context so your milage may vary.

If you're a hardware vendor and would like to have a device become a reference platform by actively participating and testing Fedora IoT,
please reach out to https://fedoraproject.org/wiki/User:Pbrobinson[Peter Robinson], the Fedora IoT Lead.

== Required Resources
The current images are 4GB in size and tested with 1GB of RAM.
The Fedora IoT base image should be able to run with less resources, but of course this will limit the amount of container applications that can be run on top of the base OS.

== Download Image

Fedora IoT images are available for download at the https://fedoraproject.org/iot/download[Download Fedora IoT page]. There are three options available to install IoT on your device:

* Anaconda installer ISO (Fedora-IoT-ostree-XX.XX.iso ) - The traditional Fedora installer, offers an interactive graphical installation tool to configure most aspects of the system including filesystem, users and passwords.
* Disk image (Fedora-IoT-raw-XX.XX.raw.xz) - A pre-built disk image suitable for single board computers (SBC's) like the Raspberry Pi 4.
* Simplified Provisioning ISO (Fedora-IoT-provisioner-XX.iso) - A new tool offering zero touch installation leveraging xref:fdo-device-setup.adoc[FIDO Device Onboarding] or xref:ignition-device-setup.adoc[Ignition] for configuration.

== Setup VM or Physical Device

- Follow these steps to xref:virtual-machine-setup.adoc[setup virtual machine]

- Follow these steps to xref:physical-device-setup.adoc[setup physical device]


Follow the setup instructions from xref:ignition-device-setup.adoc[ignition]
