= Welcome

Welcome to Fedora Internet of Things homepage. Fedora Internet of Things is a Fedora Edition to provide a strong foundation for IoT ecosystems. Whether you're working on a project at home, industrial gateways, smart cities or analytics with AI/ML, Fedora IoT can provide a trusted open source platform to build on. Fedora IoT rolling releases help you keep your ecosystem up-to-date.

== Why use Fedora IoT?
The operating system (OS) for IoT systems needs to be immutable and image based, where the image is fully tested centrally and signed before being deployed at scale to IoT systems. As these IoT systems are often located remotely, the OS should support atomic updates so nothing changes until the device is rebooted and rollback capability so it is easy to recover remotely if there is a failure during upgrade.

The Fedora IoT images work with https://coreos.github.io/rpm-ostree/[rpm-ostree], a hybrid image/package system. It supports package layering, which allows installation of RPMs for additional hardware support or applications. The GPG signed image based deployments scale well to very large numbers of clients. Updates are atomic with easy rollback capability.

The Fedora IoT images also have excellent support for container-focused workflows. Containers allow you to separate core OS updates from application updates as well as test and deploy different versions of applications.  The https://podman.io/[podman] container engine is light weight and ready for you to download or create containers for your home assistant, industrial gateways, or data storage and analytics.

== Is Fedora IoT for you?

If you are looking for a graphical desktop environment based on OSTree and designed for developers, look at https://fedoraproject.org/atomic-desktops/silverblue/[Fedora Silverblue].

If you are looking for a traditional dnf based operating system for your device, visit https://fedoraproject.org/[Fedora].

If you are looking for a lightweight yet powerful and scalable core OS for your Internet of Things project, you came to the right place! xref:getting-started.adoc[Get Started with Fedora IoT]!

If you are after an OS for Kubernetes there is https://fedoraproject.org/en/coreos/[Fedora CoreOS]

== Contribute to Fedora IoT Edition
For communication and contributing please see the xref:contributing.adoc[Contributing and Reporting Bugs] section.

image::iot-fedora.svg[SoC board]
