= Create Fedora IoT Release Candidates

To complete these steps you will need a valid https://docs.fedoraproject.org/en-US/fedora-accounts/user/[Fedora account], with appropriate permissions in https://koji.fedoraproject.org/koji/[Koji], the Fedora buildsystem.

Review the current compose tag used for Fedora IoT and what is currently tagged and included.

----
koji list-tagged f[release_version]-iot
----

Untag any builds currently included:

----
koji untag-build --all f[release_version]-iot [build1 build2 ...]
----

Review the upstream Fedora ticket requesting the Release Candidates for a listing of all Fedora release Blockers and Freeze Exceptions that are needed for the compose. 
- An example ticket for https://pagure.io/releng/issue/12007[Fedora 40 Beta Candidate Request].
- An example ticket for https://pagure.io/releng/issue/12060[Fedora 40 Final Candidate Request].

Add any builds specified by the Fedora QE team.

----
koji tag-build f[release_version]-iot [build1 build2 ...]
----

Compare the tagged builds with the Fedora compose tag (f40-compose):

----
koji list-tagged f[release_version]-compose
----

Log into the Fedora IoT compose host and run the compose for the pending release. Once the compose is complete, review the results for any outstanding deliverables. 

== Once the release has been declared `Go!`

When the release is signed off on Thursday after the Go/No-Go meeting. Open a ticket with [Release Engineering] to sign the deliverables. A request [example](https://pagure.io/releng/issue/11677) from Fedora 39.

Once the release is signed, from the compose host create the directory and run the script to copy the release so it can be sync'd to the Fedora mirrors. 

For the Beta release, note the destintation is the `test` directory:

----
mkdir /pub/alt/iot/test/f[release_version]
./sync-release.sh
----

For final:

----
mkdir /pub/alt/iot/test/f[release_version]
./sync-release.sh
----


